name: Automated CRYPTO Mail

on:
  push:
    branches:
      - main   # Runs immediately when you push to main
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10 AM UTC

jobs:
  send-mail:
    runs-on: windows-latest  # Needed for py command
    timeout-minutes: 4320    # Timeout after 72 hours (3 days)

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          py -m pip install --upgrade pip
          py -m pip install -r requirements.txt

      - name: Run mail script
        run: py main.py

      - name: Trigger next run after timeout or failure
        if: ${{ failure() }}  # This triggers the step only if the job fails or times out
        run: |
          echo "Job timed out or failed, re-triggering the workflow"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "trigger-next-run"}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
