name: Automated CRYPTO Mail

on:
  push:
    branches:
      - main   # Runs immediately when you push to main
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10 AM UTC

jobs:
  send-mail:
    runs-on: windows-latest  # Needed for py command


    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          py -m pip install --upgrade pip
          py -m pip install -r requirements.txt

      - name: Run mail script
        run: py main.py
